export const GET_INVESTMENT_SUCCESS = 'GET_INVESTMENT_SUCCESS'
export const GET_INVESTMENT_ERROR = 'GET_INVESTMENT_ERROR'
export const DELETE_INVESTMENT_SUCCESS = 'DELETE_INVESTMENT_SUCCESS';
export const DELETE_INVESTMENT_ERROR = 'DELETE_INVESTMENT_ERROR';